### ISSUE TITLE
readme.md installation download not link

### ISSUE THREAD

**Issue by runtimevic** [philippleidig/TcUnit-VsExtension#2]
hello @philippleidig ,
readme.md:
Installation
To install the TcUnit Visual Studio Extension, follow these steps:

Download the latest installer.

download not link...

**Comment by philippleidig** [comment]
Yes, the VS extension is still in progress. I am implementing the VS2022 support at the moment. Also waiting for a first stable version of the TcUnit-VsTestAdapter.

Planned to get a first release until christmas.

**Comment by vanoo1983** [comment]
Hello
How is the actual state of the implementation?
